"use client";

import { useState } from "react";
import { Quote, Flame, Shield, Globe, Star, ChevronLeft, ChevronRight } from "lucide-react";
import { audioEngine } from "./AudioEngine";

const REVIEWS = [
  {
    name: "Elena Rostova",
    title: "3x World Sudoku Championship Finalist",
    rank: "Sovereign #004",
    avatar: "ER",
    text: "Sudokult is unlike any puzzle application I have ever used. The candidate pencil engine is completely seamless, and the daily 00:00 UTC rite brings an intoxicating sense of global competition.",
    time: "3m 42s record on Grandmaster Rite",
  },
  {
    name: "Marcus Vance",
    title: "Logic Architect & Speedrunner",
    rank: "Hierophant #142",
    avatar: "MV",
    text: "The Technique Codex alone changed how I look at Swordfish and XY-Wing patterns. Finally a platform that respects pure mathematical deduction without gimmicks or forced ads.",
    time: "Daily Rite Streak: 184 Days",
  },
  {
    name: "Dr. Kenji Sato",
    title: "Professor of Combinatorics, Tokyo",
    rank: "Grandmaster #089",
    avatar: "KS",
    text: "The zero-guess guarantee is what sets Sudokult apart. Every single puzzle generated by their engine is guaranteed to have a unique, elegant logical path.",
    time: "Mastered 500+ Variant Grids",
  },
];

export default function TestimonialsAndLore() {
  const [activeReviewIdx, setActiveReviewIdx] = useState(0);

  const handleNextReview = () => {
    audioEngine.playClick(450);
    setActiveReviewIdx((prev) => (prev + 1) % REVIEWS.length);
  };

  const handlePrevReview = () => {
    audioEngine.playClick(450);
    setActiveReviewIdx((prev) => (prev - 1 + REVIEWS.length) % REVIEWS.length);
  };

  const currentReview = REVIEWS[activeReviewIdx];

  return (
    <section id="manifesto" className="py-24 bg-[#09090e] relative overflow-hidden">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* Section 1: The Manifesto of the 81 Seals */}
        <div className="mb-24 p-8 sm:p-12 rounded-3xl bg-glass-card border border-amber-500/30 relative overflow-hidden shadow-2xl glow-gold">
          <div className="absolute top-0 right-0 w-96 h-96 bg-amber-500/10 rounded-full blur-[100px] pointer-events-none"></div>

          <div className="max-w-3xl">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-amber-400/10 text-amber-400 font-mono text-xs mb-4">
              <Shield className="w-3.5 h-3.5" />
              <span>THE SACRED MANIFESTO</span>
            </div>

            <h2 className="text-3xl sm:text-4xl font-extrabold text-white mb-6">
              THE THREE DOGMAS OF <span className="text-gold-gradient">SUDOKULT</span>
            </h2>

            <div className="space-y-6 text-gray-300">
              <div className="flex gap-4">
                <div className="w-8 h-8 rounded-xl bg-amber-400/20 text-amber-400 font-mono font-bold flex items-center justify-center shrink-0">
                  I
                </div>
                <div>
                  <h4 className="text-white font-bold text-lg mb-1">Purity of Logic</h4>
                  <p className="text-sm text-gray-400">
                    We forbid guessing. Every seal broken in Sudokult can be deduced through pure, deterministic logic. If a cell requires a coin flip, the puzzle is unholy.
                  </p>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="w-8 h-8 rounded-xl bg-amber-400/20 text-amber-400 font-mono font-bold flex items-center justify-center shrink-0">
                  II
                </div>
                <div>
                  <h4 className="text-white font-bold text-lg mb-1">Synchronized Rites</h4>
                  <p className="text-sm text-gray-400">
                    At 00:00 UTC each day, 48,000+ mind ascetics across 94 countries receive the exact same 9x9 grid. One daily chance for immortality on the Ascendant Board.
                  </p>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="w-8 h-8 rounded-xl bg-amber-400/20 text-amber-400 font-mono font-bold flex items-center justify-center shrink-0">
                  III
                </div>
                <div>
                  <h4 className="text-white font-bold text-lg mb-1">The Flow Sanctum</h4>
                  <p className="text-sm text-gray-400">
                    Zero ads, zero clutter, zero popups. Only pure obsidian aesthetics, sound feedback, and effortless candidate note gestures.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Section 2: Grandmaster Testimonials */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
          
          <div className="lg:col-span-5">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/10 text-purple-400 font-mono text-xs mb-4">
              <Star className="w-3.5 h-3.5" />
              <span>TESTIMONIALS OF THE ORDER</span>
            </div>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-white mb-4">
              VOICES OF THE <br />
              <span className="text-purple-gradient">GRANDMASTERS</span>
            </h2>
            <p className="text-gray-400 text-sm sm:text-base mb-6">
              Hear from championship solvers and logic ascetics who have made Sudokult their daily mind sanctuary.
            </p>

            {/* Testimonial Controls */}
            <div className="flex items-center gap-3">
              <button
                onClick={handlePrevReview}
                className="p-3 rounded-xl bg-white/5 border border-white/10 hover:border-amber-400/40 text-gray-300 hover:text-amber-400 transition-colors"
              >
                <ChevronLeft className="w-5 h-5" />
              </button>
              <button
                onClick={handleNextReview}
                className="p-3 rounded-xl bg-white/5 border border-white/10 hover:border-amber-400/40 text-gray-300 hover:text-amber-400 transition-colors"
              >
                <ChevronRight className="w-5 h-5" />
              </button>
              <span className="text-xs font-mono text-gray-400 ml-2">
                {activeReviewIdx + 1} / {REVIEWS.length}
              </span>
            </div>
          </div>

          {/* Active Review Card */}
          <div className="lg:col-span-7">
            <div className="p-8 sm:p-10 rounded-3xl bg-glass-card border border-white/10 relative shadow-xl">
              <Quote className="w-12 h-12 text-amber-400/20 absolute top-6 right-6" />

              <p className="text-lg sm:text-xl text-gray-200 italic leading-relaxed mb-8">
                &ldquo;{currentReview.text}&rdquo;
              </p>

              <div className="flex items-center justify-between pt-6 border-t border-white/10">
                <div className="flex items-center gap-4">
                  <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-amber-400 to-purple-600 p-0.5">
                    <div className="w-full h-full bg-[#070709] rounded-[14px] flex items-center justify-center font-mono font-bold text-amber-400">
                      {currentReview.avatar}
                    </div>
                  </div>
                  <div>
                    <h4 className="text-white font-bold">{currentReview.name}</h4>
                    <p className="text-xs text-gray-400">{currentReview.title}</p>
                  </div>
                </div>

                <div className="text-right hidden sm:block">
                  <span className="px-2.5 py-1 rounded bg-amber-400/10 text-amber-400 font-mono text-xs font-bold">
                    {currentReview.rank}
                  </span>
                  <div className="text-[11px] text-gray-400 font-mono mt-1">
                    {currentReview.time}
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section>
  );
}
